apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: verticalpodautoscalercontrollers.autoscaling.openshift.io
spec:
  group: autoscaling.openshift.io
  names:
    kind: VerticalPodAutoscalerController
    listKind: VerticalPodAutoscalerControllerList
    plural: verticalpodautoscalercontrollers
    singular: verticalpodautoscalercontroller
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            safetyMarginFraction:
              type: number
              minimum: 0
            podMinCPUMillicores:
              type: number
              minimum: 0
            podMinMemoryMb:
              type: number
              minimum: 0
            recommendationOnly:
              type: boolean
          type: object
        status:
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
